### ISSUE TITLE
pipeline

### ISSUE THREAD

**Issue by Sadegh-Kalami** [Wallong/VINS-GPS-Wheel#10]
Hello,
thanks to your great job.
Iam new i wanted to know is there anyway to turn off wheel and just use Visual-Intertia + GPS data ?

**Comment by zhh2005757** [comment]
Maybe you can refer to VINS-Fusion directly, which fuses visual-inertial and gps data.

**Comment by Sadegh-Kalami** [comment]
as far as I know, VINS-Fusion doesn't use GPS data. It only uses Visual and Inertial Data.

**Comment by zhh2005757** [comment]
No, it does has a global fusion with gps, you can check the paper and the source code

**Comment by Sadegh-Kalami** [comment]
You are so true. I had made a mistake.
Thanks <3
