### ISSUE TITLE
好像没有头文件<custom_msgs/Encoder.h>？

### ISSUE THREAD

**Issue by bobododosjl** [Wallong/VINS-GPS-Wheel#2]

**Comment by Blithe98** [comment]
这个文件在编译的过程中会生成。
![2021-11-01 14-16-00 的屏幕截图](https://user-images.githubusercontent.com/44455762/139629639-129f0583-b57e-43b2-b21b-b0dcaf4afee7.png)

**Comment by Wallong** [comment]
出现这种情况catkin_make 多遍即可
