### ISSUE TITLE
编码器预积分残差公式

### ISSUE THREAD

**Issue by bill4u** [Wallong/VINS-GPS-Wheel#6]
你好，感谢你的开源工作。有一个问题跟你请教一下：

根据Visual-Inertial Odometry Tightly Coupled with Wheel Encoder Adopting Robust Initialization and Online Extrinsic Calibration论文，残差公式应该是：
residuals.block<3, 1>(9, 0) = Qi.inverse() * (Pj - Pi) - TIO + Qi.inverse() * Qj * TIO - corrected_delta_eta;
但是在你的代码里面却把它注释掉并换成另一个公式了，请问这个处理的原因是什么呢？

另外请问是否可以添加微信好友，向你请教其他问题呢？
if(可以)
     bill4u@126.com是我的个人邮箱，不介意的话可以发一个微信加好友的二维码截图;
else
     { 直接忽略; return 0; }

**Comment by Wallong** [comment]
你好，感谢你的来信。
上周太忙，来不及回复。这两个公式是等价的，论文中的是运算过的公式，代码中保留的是运算之前的，可以更清晰一眼看到公式的由来。两者是一样的。


微信号：clifton_wang




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wallong/VINS-GPS-Wheel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月15日(星期二) 下午3:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Wallong/VINS-GPS-Wheel] 编码器预积分残差公式 (Issue #6)





 
你好，感谢你的开源工作。有一个问题跟你请教一下：
 
根据Visual-Inertial Odometry Tightly Coupled with Wheel Encoder Adopting Robust Initialization and Online Extrinsic Calibration论文，残差公式应该是：
 residuals.block<3, 1&gt;(9, 0) = Qi.inverse() * (Pj - Pi) - TIO + Qi.inverse() * Qj * TIO - corrected_delta_eta;
 但是在你的代码里面却把它注释掉并换成另一个公式了，请问这个处理的原因是什么呢？
 
另外请问是否可以添加微信好友，向你请教其他问题呢？
 if(可以)
 ***@***.***是我的个人邮箱，不介意的话可以发一个微信加好友的二维码截图;
 else
 { 直接忽略; return 0; }
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
