### ISSUE TITLE
请问一下KAIST数据集要怎么下载呢？

### ISSUE THREAD

**Issue by sjtuyinjie** [Wallong/VINS-GPS-Wheel#7]
github上给的链接打不开哎。开了梯子也上不去

**Comment by Wallong** [comment]
https://drive.google.com/drive/mobile/folders/1EyGkWunjlfWWT7k8zDDbAnbbpHO9rmGK?usp=sharing
KAIST官方申请得到的

**Comment by aimilios-cell-labs** [comment]
hello, could you maybe also provide this data as a bag file ? otherwise how you running the ros package with this data? 
thanks

> https://drive.google.com/drive/mobile/folders/1EyGkWunjlfWWT7k8zDDbAnbbpHO9rmGK?usp=sharing KAIST官方申请得到的
