### ISSUE TITLE
公式推导

### ISSUE THREAD

**Issue by chengwei0427** [Wallong/VINS-GPS-Wheel#8]
你好，
请问在博客中![image](https://user-images.githubusercontent.com/20199999/168203148-06da946f-bf79-451a-8f81-2f4e01015492.png)推导部分，如下[第一行到第二行]公式是怎么推导的

![image](https://user-images.githubusercontent.com/20199999/168203086-f79a25e0-2f91-46dc-b97f-ccb318264444.png)

**Comment by Wallong** [comment]
![image](https://user-images.githubusercontent.com/13499067/168221168-1d954829-3d60-45fe-b389-4ddc65af9aaa.png)

**Comment by chengwei0427** [comment]
感谢解答；
